name: tests runner

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: ./i8080_tests
      run: ./i8080_tests
